apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ec2nodeclass.yaml
  - nodepool-application.yaml
  - nodepool-monitoring.yaml
  - ec2nodeclass-test.yaml
  - nodepool-application-test.yaml
  - nodepool-monitoring-test.yaml
